<?php
/**
 * Plugin Name: Chystota: Count Responces
 * Plugin URI:
 * Description: This widget displays how many people liked your page and work.
 * Version: 1.0
 * Author: chystota
 * Author URI: makecodework@gmail.com
 *
 */

add_action( 'widgets_init', 'chystota_response_count_widgets' );

function chystota_response_count_widgets(){
	register_widget( 'chystota_response_count_widget' );
}

class chystota_response_count_widget extends WP_Widget {

	public function __construct( ) {
		$widget_ops = [
			'classname'     => 'f_widget',
			'description'   => __( 'Displays how many people liked your page and work.', 'chystota' )
		];
		parent ::__construct( 'chystota_response_count_widget',__( 'Chystota: Responce count', 'chystota' ), $widget_ops);
	}

	public function widget( $args, $instance ) {
		// TODO: Change the autogenerated stub
		extract( $args );
		$title = apply_filters( 'widget_title', $instance['title'] );
		$chystota_facebook_id = $instance['chystota_facebook_id'];
		$appsecret = $instance['appsecret'];
		$chystota_google_id = $instance['chystota_google_id'];

        if( $chystota_google_id  ) {
            echo 'hello';
        }


		if( $chystota_facebook_id ){
			$apiUrl = 'https://graph.facebook.com/'.$chystota_facebook_id.'?fields=fan_count.summary(true)&access_token='.$appsecret;
			//open connection
			$ch = curl_init();
			$timeout=5;
			//set the url
			curl_setopt($ch,CURLOPT_URL, $apiUrl);
			curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
			curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
			curl_setopt($ch, CURLOPT_SSL_VERIFYPEER,false);
			//execute post
			$result = curl_exec($ch);
			//close connection
			curl_close($ch);
			$data = json_decode($result,true);
        }

		?>

        <div class="reviews">
            <div class="container">
                <div class="row">
                    <div class="col">
				        <?php if( !empty($title) ):?>
                            <h2><?php echo $title; ?></h2>
				        <?php endif;?>
                    </div>
                </div>
            </div>
    	<div class="review-block">
            <div class="icon">
                <a class="fb" href="https://facebook.com/share.php?u=<?php echo get_site_url(); ?>" target="_blank">
                    <i class="fab fa-facebook-square"></i>
                </a>
                <span>Google</span>
                <span class="review_number">4.8</span>
            </div>
            <div class="review_line">
                <progress max="5" value="4">
                    <strong>Progress: 90% done.</strong>
                </progress>
            </div>

            <div class="review_count">
			    <?php echo __( 'Based on '. number_format($data['fan_count']).' reviews', 'chystota' )  ;?>
            </div>

		</div>
            <?php if( $chystota_facebook_id ) :?>
                <div class="review-block">
                    <div class="icon">
                        <a class="fb" href="https://facebook.com/share.php?u=<?php echo get_site_url(); ?>" target="_blank">
                            <i class="fab fa-facebook-square"></i>
                        </a>
                        <span>Facebook</span>
                        <span class="review_number">5.0</span>
                    </div>
                    <div class="review_line">
                        <progress max="5" value="5">
                            <strong>Progress: 90% done.</strong>
                        </progress>
                    </div>

                    <div class="review_count">
			            <?php echo __( 'Based on '. number_format($data['fan_count']).' reviews', 'chystota' )  ;?>
                    </div>
                </div>
            <?php endif; ?>
        </div>
		<?php
	}

	public function update( $new_instance, $old_instance ) {
		return parent ::update( $new_instance, $old_instance ); // TODO: Change the autogenerated stub
	}                     

	public function form( $instance ) {
		// TODO: Change the autogenerated stub
		$defaults = array (
		        'title' => '',
                'appsecret' => '',
                'chystota_facebook_id' => '',
                'chystota_google_id' => '');
		$instance = wp_parse_args( (array) $instance, $defaults ); ?>
		<p>
			<label for="<?php echo $this->get_field_id( 'title' ); ?>">
				<?php _e('Title:', 'chystota'); ?></label>
			<input type="text" id="<?php echo $this->get_field_id('title'); ?>" name="<?php echo $this->get_field_name('title'); ?>" value="<?php echo $instance['title']; ?>" style="width:100%;" />
		</p>
        <p>
            <label for="<?php echo $this->get_field_id( 'chystota_google_id' ); ?>">
				<?php _e('Google ID:', 'chystota'); ?></label>
            <input id="<?php echo $this->get_field_id( 'chystota_google_id' ); ?>" name="<?php echo $this->get_field_name( 'chystota_google_id' ); ?>" value="<?php echo $instance['chystota_google_id']; ?>" class="widefat" />
        </p>
		<p>
			<label for="<?php echo $this->get_field_id( 'chystota_facebook_id' ); ?>">
				<?php _e('Facebook Page ID:', 'chystota'); ?></label>
			<input id="<?php echo $this->get_field_id( 'chystota_facebook_id' ); ?>" name="<?php echo $this->get_field_name( 'chystota_facebook_id' ); ?>" value="<?php echo $instance['chystota_facebook_id']; ?>" class="widefat" />
		</p>
        <p>
            <label for="<?php echo $this->get_field_id( 'appsecret' ); ?>">
				<?php _e('Facebook Access Token:', 'chystota'); ?></label>
            <input id="<?php echo $this->get_field_id( 'appsecret' ); ?>" name="<?php echo $this->get_field_name( 'appsecret' ); ?>" value="<?php echo $instance['appsecret']; ?>" class="widefat" />
        </p>


		<?php
	}
}

// end class